config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :posts, only: [:index, :show]
  resources :projects, only:[:index, :show]
  resources :contacts, only:[:new, :create]

  namespace :admin do

    root 'welcome#index'
    resources :posts, :projects
    resources :contacts, only:[:new, :create]

    get '/login' => 'sessions#new'
    get '/logout' => 'sessions#destroy'
    post '/login' => 'sessions#create'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
    :subject => "Contact Form",
    :to => "bmwf6@abv.bg",
    :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/project.rb
class Project < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin/application'

  before_action :ensure_authenticated!

  private
  def ensure_authenticated!
    redirect_to admin_login_path unless admin_signed_in?
  end

  def current_admin
    if session[:admin_id]
      @current_admin ||= Admin.find(session[:admin_id]) rescue nil
    end
  end

  def admin_signed_in?
    !current_admin.nil?
  end

  helper_method :current_admin, :admin_signed_in?
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < Admin::BaseController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send messeage.'
      render :new
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new (post_params)
    if @post.save
      redirect_to admin_root_path, notice: "Post succsesfully saved"
    else
      redirect_to admin_root_path
    end
  end

  def edit
  end

  def update
    if @post.update (post_params)
      redirect_to admin_root_path, notice: "Post was succsesfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
      redirect_to admin_root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :slug)
    end

    def find_post
      @post = Post.friendly.find(params[:id])
    end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  before_action :find_project, only:[:show, :edit, :update, :destroy]
  def index
    @projects = Project.all.order("created_at DESC")
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new (project_params)
    if @project.save
      redirect_to admin_projects_path, notice:"Project was succsesfully created!"
    else
      render 'new', notice: "Somethign went wrong!"
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to admin_projects_path, notice: "Project was succsesfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
      redirect_to admin_projects_path
  end

  private
    def project_params
      params.require(:project).permit(:title, :body, :link, :slug)
    end

    def find_project
      @project = Project.friendly.find(params[:id])
    end
end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < Admin::BaseController

  def index
    @posts = Post.all.limit(3).order("created_at DESC")
    @projects = Project.all.limit(3).order("created_at DESC")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send messeage.'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def show
  end

  private

    def find_post
      @post = Post.friendly.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only:[:show]
  def index
    @projects = Project.all.order("created_at DESC")
  end

  def show
  end

  private
    def find_project
      @project = Project.friendly.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.all.limit(3).order("created_at DESC")
    @projects = Project.all.limit(3).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin/_footer.haml
%footer#main_footer
  %p.copyright &copy; 2017 Corhax
  %nav
    %a{:href => "http://twitter.com"}
      %i.fa.fa-twitter

    %a{:href => "http://facebook.com"}
      %i.fa.fa-facebook

    %a{:href => "http://github.com"}
      %i.fa.fa-github

app/views/layouts/admin/_header.haml
%header#main_navigation.clearfix
  = link_to "Corhax", admin_root_path, class: "name"
  %nav
    =link_to "Posts", admin_posts_path
    =link_to "Projects", admin_projects_path
    =link_to "Contact", new_admin_contact_path

app/views/layouts/admin/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyBlog
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway:400,700", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/admin/header'
    .under-body
      = yield
    = render 'layouts/admin/footer'

app/views/layouts/admin/auth.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyBlog
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway:400,700", :rel => "stylesheet"}/
    = stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyBlog
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway:400,700", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/frontpage/header'
    = yield
    = render 'layouts/frontpage/footer'

app/views/layouts/frontpage/_header.haml
%header#main_navigation.clearfix
  = link_to "Corhax", root_path, class: "name"
  %nav
    =link_to "Posts", posts_path
    =link_to "Projects", projects_path
    =link_to "Contact", new_contact_path