config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :posts, only: [:index, :show]
  resources :projects, only:[:index, :show]
  resources :contacts, only:[:new, :create]

  namespace :admin do

    root 'welcome#index'
    resources :posts, :projects
    resources :contacts, only:[:new, :create]

    get '/login' => 'sessions#new'
    get '/logout' => 'sessions#destroy'
    post '/login' => 'sessions#create'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
    :subject => "Contact Form",
    :to => "bmwf6@abv.bg",
    :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/project.rb
class Project < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin/application'

  before_action :ensure_authenticated!

  private
  def ensure_authenticated!
    redirect_to admin_login_path unless admin_signed_in?
  end

  def current_admin
    if session[:admin_id]
      @current_admin ||= Admin.find(session[:admin_id]) rescue nil
    end
  end

  def admin_signed_in?
    !current_admin.nil?
  end

  helper_method :current_admin, :admin_signed_in?
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < Admin::BaseController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send messeage.'
      render :new
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new (post_params)
    if @post.save
      redirect_to admin_root_path, notice: "Post succsesfully saved"
    else
      redirect_to admin_root_path
    end
  end

  def edit
  end

  def update
    if @post.update (post_params)
      redirect_to admin_root_path, notice: "Post was succsesfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
      redirect_to admin_root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :slug)
    end

    def find_post
      @post = Post.friendly.find(params[:id])
    end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  before_action :find_project, only:[:show, :edit, :update, :destroy]
  def index
    @projects = Project.all.order("created_at DESC")
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new (project_params)
    if @project.save
      redirect_to admin_projects_path, notice:"Project was succsesfully created!"
    else
      render 'new', notice: "Somethign went wrong!"
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to admin_projects_path, notice: "Project was succsesfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
      redirect_to admin_projects_path
  end

  private
    def project_params
      params.require(:project).permit(:title, :body, :link, :slug)
    end

    def find_project
      @project = Project.friendly.find(params[:id])
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController
  layout 'admin/auth'
  skip_before_action :ensure_authenticated!, except: :destroy


  def new
    @admin = Admin.new
  end

  def create
    admin = Admin.find_by_email(admin_params[:email])
    if admin && admin.authenticate(admin_params[:password])
      session[:admin_id] = admin.id
      redirect_to admin_root_path, notice: "Successfuly Login!"
    else
      @admin = Admin.new
      flash.now[:alert] = "There was error signing you in!"
      render "new"
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to root_path, notice: "Successfuly logout"
  end

  private
  def admin_params
    params.require(:admin).permit(:email, :password)
  end
end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < Admin::BaseController

  def index
    @posts = Post.all.limit(3).order("created_at DESC")
    @projects = Project.all.limit(3).order("created_at DESC")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send messeage.'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def show
  end

  private

    def find_post
      @post = Post.friendly.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only:[:show]
  def index
    @projects = Project.all.order("created_at DESC")
  end

  def show
  end

  private
    def find_project
      @project = Project.friendly.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.all.limit(3).order("created_at DESC")
    @projects = Project.all.limit(3).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/contacts/create.haml
%h1#page_title Hello

.skinny_wrapper.wrapper_padding
  %h1 Thank you for your message
  %p I'll get back to you soon.

app/views/admin/contacts/new.haml
%h1#page_title Contact Me

.skinny_wrapper.wrapper_padding
  = form_for @contact do |f|

    = f.label :name
    %br
    = f.text_field :name, required: true

    %br

    = f.label :email
    %br
    = f.email_field :email, required: true

    %br

    = f.label :message
    %br
    = f.text_area :message, as: :text

    .hidden
      = f.label :nickname
      %br
      = f.text_field :nickname, hint: 'leave this field blank'

    = f.submit 'Send Messeage', class: "button"

app/views/admin/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://bloggywebsite.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/admin/posts/_form.haml
= form_for [:admin, @post] do |f|
  - if @post.errors.any?
    %h2
      = pluralize(@post.errors.count, "error")
      prevted this post from saving:
    %ul
      - @post.errors.full_messages.each do |msg|
        %li= msg

  = f.label :title
  %br
  = f.text_field :title

  %br
  %br

  = f.label :content, "Write your article here"
  %br
  = f.text_area :body

  %br
  %br

  = f.submit

app/views/admin/posts/edit.haml
%h1#page_title Edit post

.skinny_wrapper.wrapper_padding
  = render 'form'

app/views/admin/posts/index.haml
%h1#page_title My Posts

#posts_wrapper.skinny_wrapper
  - @posts.each do |post|
    .post
      %p.date= post.created_at.strftime('%A, %B %d')
      %h2
        = link_to post.title, admin_post_path(post)
      %hr

= paginate @posts
= link_to "New", new_admin_post_path

app/views/admin/posts/new.haml
%h1#page_title Create posts
.skinny_wrapper.wrapper_padding
  = render 'form'

app/views/admin/posts/show.haml
#post_show_content.skinny_wrapper.wrapper_padding
  %header
    %p.date= @post.created_at.strftime('%A, %B %d')
    %h1= @post.title
    %hr

  #content
    = @post.body

  %hr



  = render 'disqus'

= link_to "Edit", edit_admin_post_path(@post)
= link_to "Delete", admin_post_path,
  method: :delete, data: { confirm: "Are you sure?" }

app/views/admin/projects/_form.haml
= form_for [:admin, @project] do |f|
  - if @project.errors.any?
    %h2
      = pluralize(@project.errors.count, "error")
      prevted this project from saving:
    %ul
      - @project.errors.full_messages.each do |msg|
        %li= msg

  = f.label :title
  %br
  = f.text_field :title

  %br
  %br

  = f.label :description
  %br
  = f.text_area :body

  %br
  %br

  = f.label :link
  %br
  = f.text_field :link

  %br
  %br

  = f.submit

app/views/admin/projects/edit.haml
%h1#page_title Edit Project

.skinny_wrapper.wrapper_padding
  = render 'form'

app/views/admin/projects/index.haml
%h1#page_title My Projects

#posts_wrapper.skinny_wrapper
  - @projects.each do |project|
    .post
      %p.date= project.created_at.strftime('%A, %B %d')
      %h2
        %a{:href => "/"}= link_to project.title, admin_project_path(project)
      %hr

= link_to "New", new_admin_project_path

app/views/admin/projects/new.haml
%h1#page_title New project

.skinny_wrapper.wrapper_padding
  = render 'form'

app/views/admin/projects/show.haml
#post_show_content.skinny_wrapper.wrapper_padding
  %header
    %p.date= @project.created_at.strftime('%A, %B %d')
    %h1= @project.title
    %hr

  #content
    = @project.body

    %br
    %br

    .button_wrapper
      %a.project_button{:href => "#{@project.link}", :target => "_blank"}
        Visit #{@project.title}
  %hr

= link_to "Edit", edit_admin_project_path
= link_to "Delete", admin_project_path,
  method: :delete, data: { confirm: "Are you sure?" }

app/views/admin/welcome/index.haml
.wrapper.wrapper_padding.clearfix

  .col-1.about.homepage_content
    %h2 About me
    %hr
    %p My name is Dimitar Dimitrov 18 years old from Bulgaria i am learning Ruby on Rails and this is the project i've made to show my works. If you want to reach me, you can do it in the contact page send me email and i will answer when i can!

  .col-2.homepage_content
    %h2 My Posts
    %hr

    - @posts.each do |post|
      %h3= link_to post.title, admin_post_path(post)
      %p.date= post.created_at.strftime("%A, %b %d")

  .col-3.homepage_content
    %h2 My Work
    %hr
      - @projects.each do |project|
        %h3= link_to project.title, admin_project_path(project)
        %p.date= project.created_at.strftime("%A, %b %d")

app/views/posts/_form.haml
= form_for @post do |f|
  - if @post.errors.any?
    %h2
      = pluralize(@post.errors.count, "error")
      prevted this post from saving:
    %ul
      - @post.errors.full_messages.each do |msg|
        %li= msg

  = f.label :title
  %br
  = f.text_field :title

  %br
  %br

  = f.label :content, "Write your article here"
  %br
  = f.text_area :body

  %br
  %br

  = f.submit

app/views/posts/edit.haml
= render 'form'

app/views/posts/index.haml
%h1#page_title Stuff I've writeen

#posts_wrapper.skinny_wrapper
  - @posts.each do |post|
    .post
      %p.date= post.created_at.strftime('%A, %B %d')
      %h2
        %a{:href => "/"}= link_to post.title, post
      %hr

= paginate @posts

app/views/posts/show.haml
#post_show_content.skinny_wrapper.wrapper_padding
  %header
    %p.date= @post.created_at.strftime('%A, %B %d')
    %h1= @post.title
    %hr

  #content
    = @post.body

  %hr

  #share_box
    %p Share To do list
    %i.fa.fa-twitter
    %i.fa.fa-facebook

  %hr

  = render 'disqus'

= link_to "Edit", edit_post_path(@post)

app/views/projects/_form.haml
= form_for @project do |f|
  - if @project.errors.any?
    %h2
      = pluralize(@project.errors.count, "error")
      prevted this project from saving:
    %ul
      - @project.errors.full_messages.each do |msg|
        %li= msg

  = f.label :title
  %br
  = f.text_field :title

  %br
  %br

  = f.label :description
  %br
  = f.text_area :body

  %br
  %br

  = f.label :link
  %br
  = f.text_field :link

  %br
  %br

  = f.submit

app/views/projects/index.haml
%h1#page_title Stuff i build

#posts_wrapper.skinny_wrapper
  - @projects.each do |project|
    .post
      %p.date= project.created_at.strftime('%A, %B %d')
      %h2
        %a{:href => "/"}= link_to project.title, project
      %hr

app/views/projects/show.haml
#post_show_content.skinny_wrapper.wrapper_padding
  %header
    %p.date= @project.created_at.strftime('%A, %B %d')
    %h1= @project.title
    %hr

  #content
    = @project.body

    %br
    %br

    .button_wrapper
      %a.project_button{:href => "#{@project.link}", :target => "_blank"}
        Visit #{@project.title}
  %hr

  = link_to "Edit", edit_project_path(@project)
  = link_to "Delete", project_path(@project), method: :delete,
        data: { confirm: "Are you sure ?" }

app/views/welcome/index.haml
.wrapper.wrapper_padding.clearfix

  .col-1.about.homepage_content
    %h2 About
    %hr
    %p Lorem ipsum...

  .col-2.homepage_content
    %h2 Stuff I've Written
    %hr

    - @posts.each do |post|
      %h3= link_to post.title, post
      %p.date= post.created_at.strftime("%A, %b %d")

  .col-3.homepage_content
    %h2 Stuff I've Built
    %hr
      - @projects.each do |project|
        %h3= link_to project.title, project
        %p.date= project.created_at.strftime("%A, %b %d")